### ISSUE TITLE
r4-pro.com bl2ck

### ISSUE THREAD

**Issue by Deletecat** [DS-Homebrew/flashcard-archive#12]
It appears that the gold label r4-pro.com cart works with bl2ck. A while ago I asked a person with this cart to test it, they said that it [worked for them](https://www.reddit.com/r/flashcarts/comments/xb9prn/comment/iojrmcl/) . Would this be added to the bl2ck compatibility list or would there need to be more testing?

**Comment by lifehackerhansol** [comment]
omg kitcat hi

The three things needed to check are whether a) kernel boots, b) games boot, and c) homebrew boots. Basic things. Though I see no one complaining, so I'll double check later today.

We actually had to remove a certain cart the other day because games didn't work on it. Unfortunate but oh well.

**Comment by Deletecat** [comment]
`omg Kitcat hi`
Hello! 👋

Yeah that makes sense then, I would try to message the person who tried bl2ck, but it looks as though it's a burner account :( If someone else has the cart though, I'll ask them to try it!

**Comment by Deletecat** [comment]
I found [someone else with this cart](https://www.reddit.com/r/flashcarts/comments/108dh36/which_of_these_is_the_best_r4_for_my_old_3ds_with/) who would be fine with testing bl2ck. Is there any games/homebrew in specific that should be used?

**Comment by lifehackerhansol** [comment]
Literally anything.

**Comment by Deletecat** [comment]
[It appears to work](https://www.reddit.com/r/flashcarts/comments/108dh36/which_of_these_is_the_best_r4_for_my_old_3ds_with/j41fnl4)! Bl2ck boots, games boot and homebrew also boots
