### ISSUE TITLE
r4i-sdhc.com

### ISSUE THREAD

**Issue by CJthisis** [DS-Homebrew/flashcard-archive#16]
http://r4i-sdhc.com/downloade.asp

This website has a lot of resources, like kernels for different cards with pictures on how to identify them.
When you scroll down, it also has themes and links to updated cheat bases (although I dont know how much of them is up to date).

I can also scrape all of the relevant data off the site if you want me to, you just have to ask.

Also, I just found a complete capture of the site on archive.org, with at least some downloads working, I have not tested them all though.

If this is a duplicate of r4isdhc.com from the archive, I apologise.

**Comment by lifehackerhansol** [comment]
Not worth taking anything from here, as every cart released by this website is better off with YSMenu.

And we can't share YSMenu here. But GBAtemp has a somewhat ok guide on installing it anyway.
