### ISSUE TITLE
Missing r4isdhc.com.cn 2021 or newer

### ISSUE THREAD

**Issue by nicola02nb** [DS-Homebrew/flashcard-archive#18]
I'm not finding files for my r4isdhc.com.cn 2021

**Comment by lifehackerhansol** [comment]
As per README.txt on the front page, r4isdhc.com.cn cards use the Ace3DS+/R4iLS kernel.

https://flashcard-archive.ds-homebrew.com/Ace3DS+_R4iLS/Ace3DS+_R4iLS_Wood_R4_1.62.7z
