### ISSUE TITLE
R4i 3DS Gold Plus Not Working with Wood Firmware

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/flashcard-archive#2]
I was told the R4i 3DS Gold Plus uses the Wood Kernel but when I tried to load the Kernel all I get is a black screen. When I try to load the Kernel from the website though it works fine.

**Comment by lifehackerhansol** [comment]
R4i Gold 3DS Plus uses 1.64 in r4ids.cn. If that doesn't work, basic formatting/troubleshooting etc.

Not having issues with mine (as in, it boots, but it doesn't load games because I have the defective R4i Gold 3DS+)

**Comment by DraconicNEO** [comment]
> 
> 
> R4i Gold 3DS Plus uses 1.64 in r4ids.cn. If that doesn't work, basic formatting/troubleshooting etc.
> 
> Not having issues with mine (as in, it boots, but it doesn't load games because I have the defective R4i Gold 3DS+)

Oh I see, Thankfully mine does boot games, although I'm not sure how compatible the Saves, themes, and homebrew is between the two versions.

**Comment by lifehackerhansol** [comment]
So the r4ids.cn 1.64 kernel is working as expected, then?

**Comment by DraconicNEO** [comment]
> 
> 
> So the r4ids.cn 1.64 kernel is working as expected, then?

It doesn't seem to detect the old saves properly, Nevermind It has a different Save format selected by default than the original. Other than that it seems to work fine.

**Comment by DraconicNEO** [comment]
I'm going to close this, I may post an update later if I find something broken.

**Comment by lifehackerhansol** [comment]
To clarify, all Wood kernels uploaded here I changed to `.sav` by default because a) `.nds.sav` was a mistake, and b) allows moving saves to other platforms nice and easy since you don't have to rename like 30 files just to copy them to TWiLight Menu++ or something.

**Comment by DraconicNEO** [comment]
> 
> 
> To clarify, all Wood kernels uploaded here I changed to `.sav` by default because a) `.nds.sav` was a mistake, and b) allows moving saves to other platforms nice and easy since you don't have to rename like 30 files just to copy them to TWiLight Menu++ or something.

Oh, well not sure why that happened then ¯\_(ツ)_/¯
