### ISSUE TITLE
Ace3DS+ Kernel Moonshell missing R4TF.nds

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/flashcard-archive#3]
Hello I'd like to let you know that the Moonshell version included in the Ace3DS+ archive lacks the `R4TF.nds` file which prevents it from returning to the Firmware.

**Comment by lifehackerhansol** [comment]
I'll have to play with this. I'm not too familiar with Moonshell reboot to main kernel. I know the feature exists, though.

Do you know what the R4TF.nds needs to be, specifically?

**Comment by DraconicNEO** [comment]
> 
> 
> I'll have to play with this. I'm not too familiar with Moonshell reboot to main kernel. I know the feature exists, though.
> 
> Do you know what the R4TF.nds needs to be, specifically?

A copy of the wood kernel main executable. I think it may need to be decrypted because when I tried renaming it it just crashed. It did work on a different Kernel though so I know the feature actually works.

**Comment by lifehackerhansol** [comment]
It definitely needs to be decrypted. I'll play around and see what I get.

**Comment by lifehackerhansol** [comment]
Trying a bootstrap that directly launches a decrypted kernel located on root seems to fail, placed it in `/moonshl2/resetmse/r4tf.nds`

I should play with the resetmse source.

**Comment by DraconicNEO** [comment]
> 
> 
> It definitely needs to be decrypted. I'll play around and see what I get.

Funny though because on My other cart I was able to Just rename it and it worked fine. It uses a later version of Wood Firmware, I wonder why the earlier versions of Wood are encrypted anyway...

**Comment by MushGuyDS** [comment]
Now that I remember, in the AOS repack that used to be available here, there was an r4tf.nds file in the resetmse folder that worked with AOS, but not with the "lite" version for some reason (it was supposed to redirect to either _DSMENU.DAT or _DS_MENU.DAT either way). Was this the reason it was removed?

Also, I found [this collection](https://n2s.altervista.org/wp-content/uploads/2010/01/softreset_for_Moonshell2.zip) of Moonshell soft reset files, and I tried the files named r4tf in it with no luck. Perhaps you could look into them?
