### ISSUE TITLE
WarioWare DIY and Jam with the Band fix for Blue Gateway and Ace3DS+ and R4iLS clones

### ISSUE THREAD

**Issue by davidmorom** [DS-Homebrew/flashcard-archive#36]
WarioWare DIY and Jam with the Band had always been problematic in these flashcarts, as the save type they use is not correctly supported by the kernel, due to a very stupid bug.

Recently I managed to patch this bug and both games now work perfectly. The change is just one instruction modification, from "mov r6,#0x9" to "mov r6,#0x0". This change prevents a 9 bits logical left shift on the save file sector addresses list, which is not needed at all, and is the reason that makes the games not compatible.

I leave a link to the patched kernels, in case the repository maintainer wants to merge them in some way to the archive (maybe not removing the original ones, but adding the patched ones with a note explaining the difference).

[https://mega.nz/file/ChpGwCTC#VnViroecqJMR4wss4h_X1jGl9DN0Ipvi7bk28JS9mXs](https://mega.nz/file/ChpGwCTC#VnViroecqJMR4wss4h_X1jGl9DN0Ipvi7bk28JS9mXs)

**Comment by lifehackerhansol** [comment]
Do you have an IPS patch or something to compare the decrypted output? Or the offset of the opcode?

**Comment by davidmorom** [comment]
Of course! This is the technical explanation, as far as I understand it. I am not, by any means, ARM or DS expert; this is my first time looking at ARM assembly, indeed. I didn't even know a 16 bits instructions subset exists (Thumb), and this took me a while to figure it out.

The offending instruction is at offset 0x18294 of the decrypted "_DSMENU.DAT" file, or offset 0x20184E4 of ARM9 runtime memory. The assembly code of the whole function where the instruction belongs to, is the following. This function generates the list of sectors that compose the "sav" file, which is later written to the "sav.fix" file.

```
:020184E0 2800 cmp r0,#0x0
:020184E2 D101 bne 020184E8
:020184E4 2609 mov r6,#0x9     <----- Offending instruction, must be changed to "mov r6,#0x0"
:020184E6 E000 b 020184EA
:020184E8 2600 mov r6,#0x0
:020184EA 1C28 mov r0,r5
:020184EC A901 add r1,SP,#0x4
:020184EE F00A bl 020229DC
:020184F0 FA75 ----
:020184F2 2800 cmp r0,#0x0
:020184F4 D012 beq 0201851C
:020184F6 2101 mov r1,#0x1
:020184F8 1C28 mov r0,r5
:020184FA 466A mov r2,r13
:020184FC F00A bl 02022A10
:020184FE FA88 ----
:02018500 1C01 mov r1,r0
:02018502 2800 cmp r0,#0x0
:02018504 D00A beq 0201851C
:02018506 2300 mov r3,#0x0
:02018508 E004 b 02018514
:0201850A 9A00 ldr r2,[SP,#0x0]
:0201850C 189A add r2,r3,r2
:0201850E 40B2 lsl r2,r6        <----- Other solution would be to NOP this instruction
:02018510 C404 stmia r4!,{r2}
:02018512 3301 add r3,#0x1
:02018514 9A01 ldr r2,[SP,#0x4]
:02018516 4293 cmp r3,r2
:02018518 D2EE bcs 020184F8
:0201851A E7F6 b 0201850A
:0201851C B003 add SP,#0xc
:0201851E BDF0 pop
```

This assembly seems to correspond with the following C code I extracted from [https://github.com/ahezard/woodrpg_forwarder/blob/master/akmenu4/arm9/source/save64m.cpp](https://github.com/ahezard/woodrpg_forwarder/blob/master/akmenu4/arm9/source/save64m.cpp)

```
void cSave64m::IterateFileCluster(int aFileDes,u32* aFatMap)
{
  u32 sectorsPerCluster;
  u32 shift=isSDHC()?0:9;
  if(ELM_SectorsPerClusterFromHandle(aFileDes,&sectorsPerCluster))
  {
    u32 cluster=1;
    while(true)
    {
      u32 sector;
      cluster=ELM_GetFAT(aFileDes,cluster,&sector);
      if(!cluster) break;
      for(u32 ii=0;ii<sectorsPerCluster;ii++)
        *aFatMap++=(sector+ii)<<shift;
    }
  }
}
```

This code is supposed to only shift the sector numbers when a non SDHC card is used, but for whatever reason they are always shifted (shift=9 always). But it is even worse, because even if you use a non SDHC card, the game doesn't work either, as the "sav.fix" file is mean to always contain sector numbers. The 9 bits shift is done at runtime, only when a non SDHC card is used.

I think the original developers, at some time, refactored the way they managed the difference between HC and non-HC cards, but they forgot about this part of the code. Who knows.

**Comment by lifehackerhansol** [comment]
Based on what you say, it's likely the actual reason is that the Ace3DS+ kernel is just a GPL-violating fork of the actual Wood R4 (mostly common knowledge), and the original R4 only supports bytewise addressing.
And to do bytewise addressing you need to <<9...

Thanks, I can probably improve on this a bit.
