### ISSUE TITLE
Missing M3 Real / M3i Zero firmware

### ISSUE THREAD

**Issue by RibShark** [DS-Homebrew/flashcard-archive#4]
This archive currently has no firmware for the above cards. Not sure what the best option is, I have heard Wood can run on these but haven't found any download and I'm not sure if it's up to date, but Sakura is readily available.

**Comment by RibShark** [comment]
Closed because I just noticed it's in the YSMenu folder for some reason (maybe that should be moved, it's kinda confusing)

**Comment by lifehackerhansol** [comment]
The reason it is in the YSMenu folder is because this cart should be running YSMenu and not the M3 kernel for much more optimized compatibility with all games and homebrew.
