### ISSUE TITLE
ndslr4.com

### ISSUE THREAD

**Issue by LunarLoony** [DS-Homebrew/flashcard-archive#5]
I have a flashcart that I don't think is listed. The box it came in has the site ndslr4.com, which is currently defunct - I took a cursory look at the site on [archive.org](https://web.archive.org/web/20090406025322/http://www.ndslr4.com/index-en.htm) and I wasn't able to download any of the firmware there. However, it does look like the firmware from r4-dsl.net (in the repo) works with this card, so my guess is that it's the same model as that with a different label.

For reference, it'll take a 32GB card just fine.

The original firmware is available from here - [linfoxdomain.com/nintendo/ds](https://www.linfoxdomain.com/nintendo/ds/) - says that this is an R4 SDHC, and they list another site (r4sdhc.com) which is also not listed in this repo. Should also point out that there seems to have been a later v2 revision in 2010, whose firmware is incompatible with this model.

Some pictures:

<img src="https://user-images.githubusercontent.com/2440723/134819364-013c9de7-e87e-4e28-a98c-fe199534a483.jpg" width="250">

<img src="https://user-images.githubusercontent.com/2440723/134819366-abc6fe4f-9e7f-4564-b227-81f080c5035f.jpg" width="250">

<img src="https://user-images.githubusercontent.com/2440723/134819367-e6b606cf-ad3f-4e6a-91a2-de346fe92664.jpg" width="250">

<img src="https://user-images.githubusercontent.com/2440723/134819368-77e66c06-ce37-4b64-a07e-e19d712feca5.jpg" width="250">

<img src="https://user-images.githubusercontent.com/2440723/134819369-a3317ac2-0aa1-4da9-b09d-2d4cf2209245.jpg" width="250">

Hope this is of use, apologies if I missed anything!

**Comment by lifehackerhansol** [comment]
R4SDHC.com is part of YSMenu. It is better to use the actual YSMenu with it: https://gbatemp.net/threads/retrogamefan-updates-releases.267243/

While the original kernel for r4sdhc.com is present in this repository, I highly recommend using YSMenu instead. I am unable to rehost YSMenu due to licensing restrictions, so I'll just leave that link above here.

ndslr4 is a tricky one that I haven't really figured out yet. Seeing as linfoxdomain suggests it is identical to the R4 SDHC, can you actually test the 1.34 kernel from linfoxdomain? I want some confirmation that it actually works before adding a note that these are identical.

**Comment by LunarLoony** [comment]
Yep, the 1.34 kernel works fine.

**Comment by lifehackerhansol** [comment]
Alright. Can you, then, test YSMenu as well? It is in the link above, and you need to use the files under `R4SDHC YSMenu` folder.

**Comment by LunarLoony** [comment]
I'll be honest, my knowledge of DS flashcarts isn't great. I've installed YSMenu, but it looks the same as 1.34 - how do I know if it's installed properly?

**Comment by lifehackerhansol** [comment]
Remember that the files _inside_ the R4SDHC YSMenu folder needs to be on the root of the SD. Don't just copy the R4SDHC YSMenu folder onto the SD.
With this cart, I believe it temporarily loads the original kernel, then reboots into YSmenu.

Menu should look something like this (image pulled straight from a google search): 
![image](https://user-images.githubusercontent.com/37358975/134821037-a046e88b-06df-42f7-a0ca-26dd83b4116e.png)

**Comment by LunarLoony** [comment]
Right, gotcha. Think I must've missed a file somewhere, because it's worked properly now. I think.

This is what I see

![IMG_20210926_201243](https://user-images.githubusercontent.com/2440723/134821144-fbde18a9-9adb-4648-8990-2549a8b13ac4.jpg)

**Comment by lifehackerhansol** [comment]
Can you try a smaller size SD? I vaguely recall these not doing too well with larger SDs in general.

**Comment by LunarLoony** [comment]
This is with a 2GB SD, the smallest one I have - should've clarified in my initial post. I only used the 32GB SD briefly to see if it'd work.

In the previous photo, that's the menu that comes up after the 1.34 kernel loads. It boots the default.nds file and has YSMenu options if I press Start, so it looks like it's worked.

**Comment by lifehackerhansol** [comment]
My guess is that it isn't doing too well with the SD IO. Why this affects this cart of all things, I don't know.

Perhaps try with the 32GB SD. Just for the sake of it.

**Comment by LunarLoony** [comment]
Yeah, you may be right - I get this error when I try to run a game (for reference, this works with the original kernel)

![IMG_20210926_202355](https://user-images.githubusercontent.com/2440723/134821421-dec4305b-d260-4089-9ee6-fcf6e9e26f85.jpg)

I'll try with the 32GB card now.

**Comment by LunarLoony** [comment]
Fresh install on the 32GB card (which, for reference, is a SanDisk Ultra SDHC Class 10) and the same thing happens. I tried with a couple of different games, and it did create a .sav for each one. I also notice that it doesn't seem to use the ttmenu INI file, since the text is nothing like the English literals section...

**Comment by lifehackerhansol** [comment]
Try the files in `R4-Clone YSMenu`.

Instructions:
Extract original kernel
Extract R4-Clone YSMenu files
boot cart, then run YSMenu.nds

**Comment by LunarLoony** [comment]
Doesn't like that one, either. Slightly different error this time...

![image](https://user-images.githubusercontent.com/2440723/134821937-bc8a0b73-8d34-4b0d-9973-edca2f59a337.png)

For the sake of argument, I copied r4dldi.dat to r4didl.dat (as it's spelt on that screen) but that didn't change anything.

**Comment by lifehackerhansol** [comment]
I am going to conclude this as it doesn't support YSmenu, then.

This means this cart is forever stuck on 1.34, which isn't great...

TWiLight Menu++ is probably the last option for it. I'll go ahead and upload the kernel.
